### ISSUE TITLE
Soduku 

### ISSUE THREAD

**Issue by tr4n0r** [frankdressel/games#1]
Ich habe 2 Problemchen gefunden.
#1 Ändert man die Größe des Browser Fenster und hat die Auswahlbox für die Zahlen offen, verschiebt sich die Position ganz an den Rand des Browser-Fensters

#2 Öffnet man mehrere Auswahlboxen für die Zahlen zur selben Zeit lassen sich die vorher geöffneten nicht mehr schließen.

Sehr schicke Sache !*daumenhoch*

**Comment by frankdressel** [comment]
Fixed with  c9810d3.
